apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectx-backend-deployment
  labels:
    app: connectx-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectx-backend
  template:
    metadata:
      labels:
        app: connectx-backend
    spec:
      containers:
        - name: connectx-backend
          image: mohamedsorour/connectx-backend
          ports:
            - containerPort: 3000
