pipeline {
    agent any
    stages {
        stage('Build and Push Docker Image') {
            steps {
                  script {
                withCredentials([usernamePassword(credentialsId: 'DockerHub', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                docker.withRegistry('', '${DOCKERHUB_USERNAME}', '${DOCKERHUB_PASSWORD}') {
                // building the backend image
                docker.build("connectx-backend:latest", "./ConnectX-Backend")
                // pushing the backend image
                docker.image("connectx-backend:latest").push("connectx-backend:latest")
                // building the frontend image
                docker.build("connectx-frontend:latest", "./ConnectX-Frontend")
                // pushing the frontend image
                docker.image("connectx-frontend:latest").push("connectx-frontend:latest")
                  }
                } 
                }
            }
        }
    }
}
