name: Build and Push Docker Images and Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ConnectX-Frontend
        uses: docker/build-push-action@v2
        with:
          context: ConnectX-Frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/connectx-frontend:latest

      - name: Build and push ConnectX-Backend
        uses: docker/build-push-action@v2
        with:
          context: ConnectX-Backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/connectx-backend:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install and configure kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          mkdir ${HOME}/.kube
          echo "${{ secrets.KUBECONFIG_CONTENTS }}" > ${HOME}/.kube/config

      # - name: Delete Old Deployments and Services
      #   run: |
      #     kubectl delete deployments connectx-backend-deployment
      #     kubectl delete deployments connectx-frontend-deployment
      #     kubectl delete svc connectx-frontend-deployment-service
      #     kubectl delete svc connectx-backend-deployment-service

      - name: Apply New Deployments and Services
        run: |
          kubectl apply -f Kubernates/ConnectX-Backend-Deployment.yaml
          kubectl apply -f Kubernates/ConnectX-Frontend-Deployment.yaml
          kubectl apply -f Kubernates/ConnectX-Backend-Deployment-Service.yaml
          kubectl apply -f Kubernates/ConnectX-Frontend-Deployment-Service.yaml
